---
title: "Diff-Mod-Comp"
author: "Maggie Schedl"
date: "3/23/2020"
output: github_document
---


# Setup
```{r}
getwd()
```

```{r}
library(dplyr)
library(tidyr)
library(genefilter)

```

Compare with Up regulated DEGs from SE and CASE?

```{r}

Up_Sig_SE <- read.table("Up_Sig_SE.txt")
Up_Sig_CASE <- read.table("Up_Sig_CASE.txt")
GYGenes <- read.csv("GYModGeneNames.csv")

Up_SElist <- rownames(Up_Sig_SE)
Up_CASElist <- rownames(Up_Sig_CASE)
GYgenes <- GYGenes$GYGeneNames

GYgenes

Up_SE_CASE_GY <- c(Up_SElist, Up_CASElist, GYgenes) 

#it's just the names, I can still use this method that works 
Up_SE_CASE_GY_list <- CASE_deseq_Matrix_Factors[which(rownames(CASE_deseq_Matrix_Factors) %in% Up_SE_CASE_GY),] #gets rid of any duplicates


#but using from the matrix, it has all the other information again we don't need
Up_SE_CASE_GY_uniq <- row.names(Up_SE_CASE_GY_list) #make just the names of the genes again

# Comparing each individual list with the combined list
# What are the ones in CA that are in the total? Gives back a list of true and falses 
Up_SElist.2 <- Up_SE_CASE_GY_uniq %in% Up_SElist
Up_CASElist.2 <- Up_SE_CASE_GY_uniq %in% Up_CASElist
GYgenes.2 <- Up_SE_CASE_GY_uniq %in% GYgenes

GYgenes.2

# Generating venn counts to plot venn diagram  
UP_SE_CASE_GYcomb <- cbind(Up_SElist.2, Up_CASElist.2, GYgenes.2)
U_SE_CASE_GY_venn <- vennCounts(UP_SE_CASE_GYcomb)
vennDiagram(U_SE_CASE_GY_venn, cex = 1,names = c("SE", "CASE", "GY"), circle.col = c("#593959", "#2e5eaa", "#c6f75c"))


```
Is this right? Is there only overlap with the up-regulated genes?????/?

Well, looking in the files those are all postive change.


Let's look at the down regulated overlap


```{r}

Down_Sig_SE <- read.table("Down_Sig_SE.txt")
Down_Sig_CASE <- read.table("Down_Sig_CASE.txt")
GYGenes <- read.csv("GYModGeneNames.csv")

Down_SElist <- rownames(Down_Sig_SE)
Down_CASElist <- rownames(Down_Sig_CASE)
GYgenes <- GYGenes$GYGeneNames

GYgenes

Down_SE_CASE_GY <- c(Down_SElist, Down_CASElist, GYgenes) 

#it's just the names, I can still use this method that works 
Down_SE_CASE_GY_list <- CASE_deseq_Matrix_Factors[which(rownames(CASE_deseq_Matrix_Factors) %in% Down_SE_CASE_GY),] #gets rid of any duplicates


#but using from the matrix, it has all the other information again we don't need
Down_SE_CASE_GY_uniq <- row.names(Down_SE_CASE_GY_list) #make just the names of the genes again

# Comparing each individual list with the combined list
# What are the ones in CA that are in the total? Gives back a list of true and falses 
Down_SElist.2 <- Down_SE_CASE_GY_uniq %in% Down_SElist
Down_CASElist.2 <- Down_SE_CASE_GY_uniq %in% Down_CASElist
GYgenes.2 <- Down_SE_CASE_GY_uniq %in% GYgenes

GYgenes.2

# Generating venn counts to plot venn diagram  
Down_SE_CASE_GYcomb <- cbind(Down_SElist.2, Down_CASElist.2, GYgenes.2)
D_SE_CASE_GY_venn <- vennCounts(Down_SE_CASE_GYcomb)
vennDiagram(D_SE_CASE_GY_venn, cex = 1,names = c("SE", "CASE", "GY"), circle.col = c("#593959", "#2e5eaa", "#c6f75c"))


```
WOah. 


